#!/usr/bin/python3

def square_matrix_simple(matrix=[]):
    new_matrix = []  # Initialize new_matrix as an empty list

    for row in matrix:
        square_row = []
        for i in row:
            square_row.append(i*i)
            return square_row
        new_matrix.append(square_row)
return new_matrix
